version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  # redis:
  #   image: redis:7.2-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - /path/to/local/data:/root/redis
  #     - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  #   environment:
  #     - REDIS_PASSWORD={REDIS_PASSWORD}
  #     - REDIS_PORT={REDIS_PORT}
  #     - REDIS_DATABASES={REDIS_DATABASE}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=${DB_SOURCE_CONTAINER}
      - ENVIRONMENT=prod
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
